### ISSUE TITLE
Avoid magic numbers

### ISSUE THREAD

**Issue by matt-lough** [BlockchainLabsNZ/beam-contracts-audit#1]
In `BeamCrowdsale.sol` there are some hard coded values, this code could be more readable/maintainable if the values were saved to a variable instead. 

The two `oraclize_query` functions contain this line:

`if (price > 1 ether + tx.gasprice*200000) return 0; // unexpectedly high price`

**Comment by ryu9827** [comment]
And the mainnet, kovan and browser-solidity address in [Line45-56](https://github.com/BlockchainLabsNZ/beam-contracts-audit/blob/3544b886cf847af0cf4c39dfa1b05d30df419813/contracts/BeamCrowdsale.sol#L45-L56) as well. We recommend that assaign them to variables to improve readabiliby/maintainability

**Comment by matt-lough** [comment]
There is a magic number `10 ** 9` on these two lines:

https://github.com/BlockchainLabsNZ/beam-contracts-audit/blob/master/contracts/BeamCrowdsale.sol#L802

https://github.com/BlockchainLabsNZ/beam-contracts-audit/blob/master/contracts/BeamCrowdsale.sol#L924

There is a variable called `increasing` which has that value saved, should those lines be using the variable? Is it the same thing? https://github.com/BlockchainLabsNZ/beam-contracts-audit/blob/master/contracts/BeamCrowdsale.sol#L497

**Comment by mikelimantara** [comment]
Fixed in https://gitlab.com/hubbleland-public/beam-smartcontract/commit/468b860833c3a9f450ce56d0efbfd1047ff2592a
