### ISSUE TITLE
Code can be simplified

### ISSUE THREAD

**Issue by ryu9827** [BlockchainLabsNZ/beam-contracts-audit#2]
https://github.com/BlockchainLabsNZ/beam-contracts-audit/blob/3544b886cf847af0cf4c39dfa1b05d30df419813/contracts/BeamCrowdsale.sol#L422
The if-revert statement can be simplified by using `require()`.
And since solidity 0.4.24 is used, you can put a message in require statement after required condition, to explicitily shout the reason of revert. More details and examples: [Solidity document](https://solidity.readthedocs.io/en/develop/common-patterns.html?highlight=require)

**Comment by mikelimantara** [comment]
Fixed in https://gitlab.com/hubbleland-public/beam-smartcontract/commit/d4c13e46e6ad18d824e88e3cebe517abd6279a7f
