### ISSUE TITLE
Function docstring not accurate to function

### ISSUE THREAD

**Issue by matt-lough** [BlockchainLabsNZ/beam-contracts-audit#3]
The `_postValidatePurchase` docstring mentions that the function should use `revert` statements to rollback when valid conditions are not met. The `_checkSeed` and `_checkSoftCap` functions do not use any reverts.

https://github.com/BlockchainLabsNZ/beam-contracts-audit/blob/master/contracts/BeamCrowdsale.sol#L873-L874

**Comment by mikelimantara** [comment]
Fixed in https://gitlab.com/hubbleland-public/beam-smartcontract/commit/468b860833c3a9f450ce56d0efbfd1047ff2592a
