### ISSUE TITLE
Prefer explicit declaration of variable types

### ISSUE THREAD

**Issue by matt-lough** [BlockchainLabsNZ/beam-contracts-audit#4]
Prefer to use explicit variables types. It is recommended to explicitly define your variable types and keep consistency. This confirms your intent and safeguards against a future when the default type changes.

https://github.com/BlockchainLabsNZ/beam-contracts-audit/blob/master/contracts/BeamToken.sol#L411

Prefer `uint256` instead of `uint`.

**Comment by mikelimantara** [comment]
Fixed in https://gitlab.com/hubbleland-public/beam-smartcontract/commit/468b860833c3a9f450ce56d0efbfd1047ff2592a
