### ISSUE TITLE
Typo in event name MenegerUpdated

### ISSUE THREAD

**Issue by matt-lough** [BlockchainLabsNZ/beam-contracts-audit#6]
https://github.com/BlockchainLabsNZ/beam-contracts-audit/blob/master/contracts/BeamToken.sol#L16
and
https://github.com/BlockchainLabsNZ/beam-contracts-audit/blob/master/contracts/BeamToken.sol#L70

**Comment by mikelimantara** [comment]
Fixed in https://gitlab.com/hubbleland-public/beam-smartcontract/commit/468b860833c3a9f450ce56d0efbfd1047ff2592a
